# Generated by Django 4.2.1 on 2023-06-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.room')),
            ],
            bases=('room.room',),
        ),
        migrations.CreateModel(
            name='KingRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.room')),
            ],
            bases=('room.room',),
        ),
        migrations.CreateModel(
            name='LuxuryRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.room')),
            ],
            bases=('room.room',),
        ),
        migrations.CreateModel(
            name='NormalRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.room')),
            ],
            bases=('room.room',),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(max_length=10),
        ),
    ]
